#### string tensors

In [3]:
import tensorflow as tf
string_tensor1=tf.constant(['hello rohan'],dtype=tf.string)
print(string_tensor1)

tf.Tensor([b'hello rohan'], shape=(1,), dtype=string)


In [5]:
string_tensor2=tf.constant('kaise ho',dtype=tf.string)
print(string_tensor2)

tf.Tensor(b'kaise ho', shape=(), dtype=string)


#### string operations

###### 1) tf.strings.length()

In [6]:
tf.strings.length(['cat','dog','deep learning'])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  3, 13])>

###### 2) tf.strings.split()

In [7]:
tf.strings.split(['hello how can i be an expert in Deep learning'])

<tf.RaggedTensor [[b'hello', b'how', b'can', b'i', b'be', b'an', b'expert', b'in', b'Deep',
  b'learning']]>

###### 3) tf.strings.join()

In [10]:
tf.strings.join(['hello',' ','good night','everyone','and','how' 'are' 'you'])

<tf.Tensor: shape=(), dtype=string, numpy=b'hello good nighteveryoneandhowareyou'>

###### 4) tf.strings.nicode_decode

In [12]:
tf.strings.unicode_decode('hello','utf8')

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([104, 101, 108, 108, 111])>

###### 5) tf.strings.unicode_encode()

In [16]:
decoded_tensor=tf.ragged.constant([22,600])
tf.strings.unicode_encode(decoded_tensor,"UTF-8")

<tf.Tensor: shape=(), dtype=string, numpy=b'\x16\xc9\x98'>

###### 6) tf.equal()

In [27]:
string1=tf.constant(['hello'],dtype=tf.string)
string2=tf.constant(['i am rohan'],dtype=tf.string)
print(tf.equal(string1,string2))

tf.Tensor([False], shape=(1,), dtype=bool)


###### 7) pattern matching
 
tf.strings.regex_full_match()

In [34]:
pat1=tf.constant("Ten")
pat2=tf.constant("ten")
print(tf.strings.regex_full_match(pat1,pat2))

tf.Tensor(False, shape=(), dtype=bool)


###### 8) tf.strings.lower

In [36]:
upper_case=tf.constant(['I Love Tensorflow But still I go with pytorch'])
print(tf.strings.lower(upper_case))

tf.Tensor([b'i love tensorflow but still i go with pytorch'], shape=(1,), dtype=string)
