#### variables in tensorflow

#### 1) creating variables

In [9]:
import tensorflow as tf
intvar=tf.Variable(5)
var1D=tf.Variable([1,2,3])
print(intvar.numpy())
print(var1D.numpy())

5
[1 2 3]


#### 2) updating variables

In [14]:
var=tf.Variable(20)
# 1) updating variables
var.assign(40)
print(var.numpy())

# 2) add to existing value
var.assign_add(5)
print(var.numpy())

# 3) sub to existing value
var.assign_sub(2)
print(var.numpy())


40
45
43


#### 3) variables in neural network

In [18]:
weights=tf.Variable(tf.random.normal([3,2]))
bias=tf.Variable(tf.zeros([2]))
print(weights.numpy())
print(bias.numpy())

[[-0.18513285  0.875117  ]
 [-0.03791446  0.92368263]
 [ 0.9340823  -0.15778154]]
[0. 0.]


#### 4). Why Variables are Important?

Store trainable parameters of ML/DL models.

Allow gradient updates (via backpropagation).

Work seamlessly with tf.GradientTape for automatic differentiation.

#### 5) changing the shape of variable

In [21]:
var=tf.Variable([1,2,3,4,5,6,7,8,9])
print(var.numpy())
# change the shape
tf.reshape(var,[3,3])

[1 2 3 4 5 6 7 8 9]


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

#### 6) changing the data type of tensor

In [24]:
var=tf.Variable([1,2,3,4,5],dtype=float)
print(var.numpy())

[1. 2. 3. 4. 5.]


#### 7) operations with variables

In [28]:
var1=tf.Variable([1,2])
var2=tf.Variable([2,2])
# addition operation
add=tf.add(var1,var2)
print(add.numpy())
# substraction operation
sub=(var1-var2)
print(sub.numpy())

[3 4]
[-1  0]


#### 8) hardware selection for variables

In [29]:
var=tf.Variable(20)
print(var.device)

/job:localhost/replica:0/task:0/device:CPU:0
