#### 1. Basic Arithmetic

In [8]:
import tensorflow as tf
a=tf.constant([1,2,3],dtype=float)
b=tf.constant([2,3,5],dtype=float)
# addition
add=tf.add(a,b)
print('additon',add.numpy())
sub=tf.subtract(a,b)
print('subtract',sub.numpy())
mul=tf.multiply(a,b)
print('multiply',mul.numpy())
div=tf.divide(a,b)
print('divide',div.numpy())

additon [3. 5. 8.]
subtract [-1. -1. -2.]
multiply [ 2.  6. 15.]
divide [0.5       0.6666667 0.6      ]


#### 2. Power & Roots

In [14]:
a=tf.constant([2,3,5,16])
# power
power=tf.pow(a,2)
print(power.numpy())
# square root
#square_root=tf.sqrt(a)
#print(square_root)

[  4   9  25 256]


#### 3. Exponentials & Logarithms

In [23]:
a=tf.constant([1,2,3],dtype=float)
# exponentials
exp=tf.exp(a)
sigmoid_activation=1/(1+tf.exp(a))
print(sigmoid_activation.numpy())
# logarithmic
log=tf.math.log(a)
print(log.numpy())

[0.26894143 0.11920292 0.04742587]
[0.        0.6931472 1.0986123]


#### 4. Rounding & Absolute

In [33]:
c=tf.constant([-1.1,2.6,3.9],dtype=float)
# abs
absoulate=tf.abs(c)
print(absoulate.numpy())
# round
Round=tf.round(c)
print(Round.numpy())
# floor
floor=tf.floor(c)
print(floor.numpy())
# ceil
ceil=tf.math.ceil(c)
print(ceil.numpy())

[1.1 2.6 3.9]
[-1.  3.  4.]
[-2.  2.  3.]
[-1.  3.  4.]


#### 5. Trigonometric Functions

In [36]:
x = tf.constant([0.0, 3.14159/2])
print(tf.sin(x).numpy())
print(tf.cos(x).numpy())
print(tf.tan(x).numpy())

[0. 1.]
[1.0000000e+00 1.2675908e-06]
[     0.  788898.1]


#### 6. Reduction Operations

In [46]:
matrix = tf.constant([[1, 2, 3], [4, 5, 6]])
print('sum',tf.reduce_sum(matrix).numpy())
print('mean',tf.reduce_mean(matrix).numpy())
print('max',tf.reduce_max(matrix).numpy())
print('min',tf.reduce_min(matrix).numpy())
print('accross rows: ',tf.reduce_sum(matrix,axis=1).numpy())

sum 21
mean 3
max 6
min 1
accross rows:  [ 6 15]


#### 7. Linear Algebra (tf.linalg)

In [54]:
M = tf.constant([[1., 2.], [3., 4.]])
# determinant
determinant=tf.linalg.det(M)
print('determinant',determinant.numpy())
# inverse
inverse=tf.linalg.inv(M)
print('inverse: ',inverse.numpy())
# matrix multiplication
mat_mul=tf.linalg.matmul(M,M)
print('matrix multiplication: ',mat_mul.numpy())

determinant -2.0
inverse:  [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]
matrix multiplication:  [[ 7. 10.]
 [15. 22.]]


#### 8. Useful Special Ops

In [62]:
a=tf.constant([2,4,6],dtype=float)
# square
print(tf.math.square(a).numpy())
# standard deviation
print(tf.math.reduce_std(a).numpy())
# variace
print(tf.math.reduce_variance(a).numpy())

[ 4. 16. 36.]
1.6329932
2.6666667
