In [63]:
import tensorflow as tf

def xavier_weight_init(fan_in,fan_out):
    limit=tf.sqrt(6/tf.add(fan_in,fan_out))
    return tf.random.uniform([fan_in,fan_out],minval=-limit,maxval=limit,dtype=tf.float64)
    
class layer:
    def forward(self,x):
        raise NotImplementedError
        
class Flatten(layer):
    def __init__(self,input_shape):
        self.input_shape=input_shape
        self.output_shape=(tf.reduce_prod(input_shape).numpy(),)
        
    def forward(self,x):
        return tf.reshape(x,x.shape[0],-1)
    
class Dense(layer):
    def __init__(self,unit=None,activation=None,dim=None):
        self.unit=unit
        self.activation=activation
        self.dim=dim
        self.w=None
        self.b=None
        
    def build(self,dim):
        self.w=xavier_weight_init(dim,self.unit)
        self.b=tf.Variable(tf.zeros([self.unit],dtype=tf.float32))
        
    def forward(self,x):
        z=tf.matmul(x,self.w)+self.b
        if self.activation=='relu':
            if z>0:
                return z
            else:
                return 0
        elif self.activation== 'sigmoid':
            return 1/(1+tf.exp(-x))
        elif self.activation== 'tanh':
            return (tf.exp(x)-tf.exp(-x))/(tf.exp(x)+tf.exp(-x)) 
        elif self.activation== 'softmax':
            return tf.nn.softmax(z)
        else:
            return z
            
            
        
        

[[ 0.63477272  0.47761248  0.28250416]
 [ 0.10992332 -0.14759331 -0.66706575]
 [ 0.60712172 -0.58411987 -0.08072545]
 [ 0.49982377 -0.75471558  0.68590621]]


In [47]:

def forward(x):
    return tf.reshape(x,[x.shape[1],-1])

In [48]:
x=tf.constant([[28,28,65],
               [2,3,7]])

fun=forward(x)
print(fun.numpy())

[[28 28]
 [65  2]
 [ 3  7]]


In [70]:
def sigmoid(x):
    return 1/(1+tf.exp(-x))


In [72]:
s=sigmoid(2.0)
print(s.numpy())

0.880797


0


In [122]:
def par_che(s):
    length=len(s)
    mid=length//2
    for forward in range(0,mid):
        backward=length-1-forward
        if s[forward] != s[backward]:
            return False
        else:
            return True
         
    

In [127]:
s='rohan'
p=par_che(s)
print(p)

False
