In [1]:
import tensorflow as tf

### 1) creating tensors

In [7]:
# constants
tensor1= tf.constant([[1,2,3],[99,77,66]])
print(tensor1)

tf.Tensor(
[[ 1  2  3]
 [99 77 66]], shape=(2, 3), dtype=int32)


In [15]:
# zeros
tensor2=tf.zeros([3,4])
tensor3=tf.ones([3,3])
print(tensor2)
print(tensor3)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [24]:
# random 
random_value_generation=tf.random.uniform([3,4],minval=0,maxval=10,dtype=float)
random_value_generation

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[9.592646  , 3.0349517 , 6.221564  , 5.6542397 ],
       [8.478395  , 3.0137992 , 4.0581617 , 8.099474  ],
       [9.106097  , 0.44441938, 1.1826575 , 2.4735057 ]], dtype=float32)>

### 2) tensor properties

In [31]:
sample_tensor=tf.constant([[12,23,55],[76,43,56]])
print("data type: ",sample_tensor.dtype)
print("shape: ", sample_tensor.shape)
print("number of diamension: ", sample_tensor.ndim)

data type:  <dtype: 'int32'>
shape:  (2, 3)
number of diamension:  2


## Sequential API

In [1]:
#importing the necessary libaraires
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

In [8]:
# building a sequential model
model=Sequential([
    Flatten(input_shape=(28,28)),#converts 28*28 input into 784 vector
    Dense(128,activation='relu'),#hidden layer
    Dense(10,activation='softmax')#output layer
])

In [10]:
# compile the model
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [26]:
# train the model

#load the dataset
from tensorflow.keras.datasets import mnist
#split the dataset
(x_train,y_train),(x_test,y_test)=mnist.load_data()
#normalize the range between 0 to 1
x_train,x_test=x_train/255.0,x_test/255.0
# train the model
model.fit(x_train,y_train,epochs=15,validation_data=(x_test,y_test))

Epoch 1/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8781 - loss: 0.4309 - val_accuracy: 0.9578 - val_loss: 0.1433
Epoch 2/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9632 - loss: 0.1228 - val_accuracy: 0.9691 - val_loss: 0.1013
Epoch 3/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9762 - loss: 0.0842 - val_accuracy: 0.9730 - val_loss: 0.0863
Epoch 4/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9826 - loss: 0.0574 - val_accuracy: 0.9732 - val_loss: 0.0847
Epoch 5/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9852 - loss: 0.0463 - val_accuracy: 0.9777 - val_loss: 0.0734
Epoch 6/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9896 - loss: 0.0352 - val_accuracy: 0.9761 - val_loss: 0.0777
Epoch 7/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9917 - loss: 0.0273 - val_accuracy: 0.9795 - val_loss: 0.0676
Epoch 8/15
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9928 - loss: 0.0232 - 

In [27]:
# evaluate the model
test_loss,test_acc=model.evaluate(x_test,y_test)
print('Test Accuracy',test_acc)
print('test loss',test_loss)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9690 - loss: 0.1171
Test Accuracy 0.9747999906539917
test loss 0.09808871895074844


In [34]:
# make predications
predictions=model.predict(x_test[:5]) #probablties of class
print(predictions)
print(predictions.argmax(axis=1))# final predicted class
print(y_test[:5])#actual labels

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[2.3290994e-12 5.8731465e-17 8.6909618e-10 2.8631357e-05 2.2111483e-16
  2.2745989e-12 1.1966887e-18 9.9997139e-01 2.6651110e-11 2.8026811e-08]
 [2.3199966e-12 6.8916123e-08 9.9999988e-01 1.8198499e-09 1.0158084e-25
  3.3715199e-13 2.4558565e-11 5.4449267e-20 1.2816405e-10 2.2320571e-18]
 [4.0583954e-09 9.9982375e-01 3.5925834e-06 6.2612787e-07 7.0896829e-07
  2.4881883e-09 4.6955046e-07 1.4476763e-04 2.6140526e-05 1.3044236e-08]
 [9.9999964e-01 7.2868257e-12 2.2866902e-07 4.8435592e-11 3.1986321e-15
  6.3625626e-11 2.3042093e-11 6.2106807e-08 3.6206974e-15 4.1302312e-10]
 [7.6213402e-12 2.4062831e-17 3.1866466e-13 1.1189756e-15 9.9999821e-01
  2.0872559e-14 5.3593588e-12 4.7379739e-10 1.4092847e-12 1.8355350e-06]]
[7 2 1 0 4]
[7 2 1 0 4]


In [2]:
import tensorflow as tf

In [3]:
(x_train,y_train),(x_test,y_test)=tf.keras.datasets.mnist.load_data()

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  