In [2]:
# creating the tensors
import tensorflow as tf
tensors=tf.constant([0,1,2,3,4,5,6,7,8,9])
print(tensors)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [5]:
# acessing the element using the slice method
tf.slice(tensors,begin=[2],size=[5])

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 3, 4, 5, 6])>

In [6]:
# pythonic slicing
tensors[:4]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3])>

In [26]:
# acessing elements in matrix
t1=tf.constant([[1,2,3,4],
                [11,22,33,44],
                [99,77,55,69]
               ])
print(t1)

tf.Tensor(
[[ 1  2  3  4]
 [11 22 33 44]
 [99 77 55 69]], shape=(3, 4), dtype=int32)


In [29]:
# acessing the first two rows
tf.slice(t1,[0,0],[2,tf.shape(t1)[1]])

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])>

In [31]:
# acessing the second column
tf.slice(t1, [0, 1], [tf.shape(t1)[0], 1])

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[ 2],
       [22],
       [77]])>

### tf.gather

In [33]:
# tf.gather - acessing specific element of data
t2=tf.constant([0,1,2,3,4,5,6,7,8,9])
print(t2)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [34]:
tf.gather(t2,indices=[0,3,7])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 3, 7])>

In [35]:
t3=tf.constant([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(t3)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [37]:
# acessing the second row
tf.gather(t3,indices=[1,0],axis=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [5, 4],
       [8, 7]])>