#### tf.reshape(tensors,shape,name=none)

In [5]:
import tensorflow as tf
t1=tf.constant([[1,2,3],
    [4,5,6],
    [7,8,9]])
print(t1)
print('shape of the tensors: ',tf.shape(t1).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
shape of the tensors:  [3 3]


In [11]:
# reshaping it into 1D tensors( vectors)
reshaped_t1=tf.reshape(t1,[9])
print(reshaped_t1)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [13]:
t2=tf.constant([1,2,3,4,5,6,7,8,9])
print(t2)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)


In [19]:
# reshaping it into 2D tensors(matrix)
reshaped_t2=tf.reshape(t2,[3,3])
print(reshaped_t2)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


#### transposition operation to reshape

In [21]:
t3=tf.constant([[1,2,3,4],
                [5,6,7,8]
])
print(t3)

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [22]:
transpose_t3=tf.transpose(t3,perm=[1,0])
transpose_t3

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])>