### 1) different shapes

In [6]:
import tensorflow as tf
t1=tf.constant([[1,2,3],
                [4,5,6]])
print(t1)
print(tf.rank(t1).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
2


In [8]:
t2=tf.constant([[11,12,13]])
print(t2)
print(tf.rank(t2).numpy())

tf.Tensor([[11 12 13]], shape=(1, 3), dtype=int32)
2


In [10]:
# performing the arithmetic operations and its ranks are same
# addition operation
t3=t1+t2
print(t3)
# substraction operation
t4=t1-t2
print(t4)

tf.Tensor(
[[12 14 16]
 [15 17 19]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[-10 -10 -10]
 [ -7  -7  -7]], shape=(2, 3), dtype=int32)


### 2) different shapes

In [17]:
# 2D matrix
t1=tf.constant([[1,2,3],
                [4,5,6]])
print(t1)
print(tf.rank(t1).numpy())
# 1D vevtor
t2=tf.constant([1,2,3])
print(t2)
print(tf.rank(t2).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
2
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
1


In [18]:
# Arithmetic operations
t3=t1+t2
print(t3)

tf.Tensor(
[[2 4 6]
 [5 7 9]], shape=(2, 3), dtype=int32)


In [20]:
t1=tf.constant([[1,2,3],
               [4,5,6]])
print(t1)
print(tf.rank(t1).numpy())
t2=tf.constant([2])
print(t2)
print(tf.rank(t2).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
2
tf.Tensor([2], shape=(1,), dtype=int32)
1


In [22]:
# Arithmetic operations
t3=t1+t2
print(t3)

tf.Tensor(
[[3 4 5]
 [6 7 8]], shape=(2, 3), dtype=int32)


In [25]:
# 3D tensor
t1=tf.constant([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               
                [[2,2,2],
                 [3,3,3],
                 [4,4,4]]])
print(t1)
print(tf.rank(t1).numpy())

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 2 2]
  [3 3 3]
  [4 4 4]]], shape=(2, 3, 3), dtype=int32)
3


In [26]:
# 2D tensor
t2=tf.constant([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(t2)
print(tf.rank(t2).numpy())

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
2


In [28]:
# adding new axis to t2
broadcasted_t2=tf.expand_dims(t2,axis=-1)
broadcasted_t2

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])>

In [29]:
t3=t1+t2
print(t3)

tf.Tensor(
[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[ 3  4  5]
  [ 7  8  9]
  [11 12 13]]], shape=(2, 3, 3), dtype=int32)
