###### tf.ragged.constant()

In [1]:
import tensorflow as tf
tensors=tf.ragged.constant([[1,2,3],
                            [4,5],
                            [6]])
print(tensors)

<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>


In [7]:
# operations we can do
print(tensors[0])
print(tensors[1,1])
#convet ragged to dense
print(tensors.to_tensor(default_value=0))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 0]
 [6 0 0]], shape=(3, 3), dtype=int32)


###### tf.RaggedTensors.from_value_rowids

In [15]:
words=[1,2,3,4,5,6,7,8,9]
words_ids=[0,0,0,0,1,1,2,2,2]
tf.RaggedTensor.from_value_rowids(values=words,value_rowids=words_ids)

<tf.RaggedTensor [[1, 2, 3, 4], [5, 6], [7, 8, 9]]>