In [3]:
import tensorflow as tf
sparse=tf.sparse.SparseTensor(
 indices=[[0,2],[2,0],[2,2]],
 values=[3,4,5],
 dense_shape=[3,3]    
)
print(sparse)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [2 0]
 [2 2]], shape=(3, 2), dtype=int64), values=tf.Tensor([3 4 5], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


###### tf.sparse.to_dense()

In [4]:
# converting back sparse to dense
tf.sparse.to_dense(sparse)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 3],
       [0, 0, 0],
       [4, 0, 5]])>

###### tf.sparse.from_dense()

In [5]:
dense=tf.constant([[0,0,1],
                   [0,3,4],
                   [0,0,5]])
print(dense)

tf.Tensor(
[[0 0 1]
 [0 3 4]
 [0 0 5]], shape=(3, 3), dtype=int32)


In [6]:
sparse_tensor=tf.sparse.from_dense(dense)
sparse_tensor

SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 1]
 [1 2]
 [2 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 3 4 5], shape=(4,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))

#### Arithmetic manipulations

In [7]:
sparse_tensor1=tf.sparse.SparseTensor(
indices=[[0,2],[1,1],[1,2],[2,0]],
values=[1,2,3,4],
dense_shape=[3,3]    
)
sparse_tensor2=tf.sparse.SparseTensor(
indices=[[1,1],[1,2],[2,1],[2,0]],
values=[1,2,3,4],
dense_shape=[3,3]    
)
print(sparse_tensor1)
print(sparse_tensor2)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 1]
 [1 2]
 [2 0]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 2 3 4], shape=(4,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))
SparseTensor(indices=tf.Tensor(
[[1 1]
 [1 2]
 [2 1]
 [2 0]], shape=(4, 2), dtype=int64), values=tf.Tensor([1 2 3 4], shape=(4,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


In [8]:
sparse_tensor3=tf.sparse.add(sparse_tensor1,sparse_tensor2)
print(sparse_tensor3)

SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 0]], shape=(6, 2), dtype=int64), values=tf.Tensor([1 3 5 4 3 4], shape=(6,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


#### sparse concatination

In [12]:
tf.sparse.concat(axis=0,sp_inputs=[sparse_tensor1,sparse_tensor2])

SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 1]
 [1 2]
 [2 0]
 [4 1]
 [4 2]
 [5 0]
 [5 1]], shape=(8, 2), dtype=int64), values=tf.Tensor([1 2 3 4 1 2 4 3], shape=(8,), dtype=int32), dense_shape=tf.Tensor([6 3], shape=(2,), dtype=int64))