In [1]:
# 1 . weight initialization using Xavier 

In [14]:
import tensorflow as tf
import numpy as np
def xavier_init(fan_in,fan_out):
    limit= tf.math.sqrt(6/tf.add(fan_in,fan_out))
    return tf.Variable(tf.random.uniform([fan_in,fan_out],minval=-limit,maxval=limit,dtype=tf.float64))
    

In [18]:
# layer 1: 4 inputs, and 5 neurons in hidden layer
fan_in=4 # 4 inputs
fan_out=5 # 5 outputs
w1=xavier_init(fan_in,fan_out)
b1=tf.Variable(tf.zeros([fan_out]))
print(w.numpy())
print(b.numpy())
# layer 2: 5 inputs and 3 neurons in hidden layer 2
w2=xavier_init(fan_out,3)
b2=tf.Variable(tf.zeros(3))
print(w1.numpy())
print(b2.numpy())

[[ 0.38990369 -0.21893522 -0.80710086  0.51586775 -0.80020083]
 [-0.51485939  0.02688113 -0.50957087 -0.31210928 -0.46096383]
 [-0.37543915 -0.09734712  0.02198224 -0.01003921 -0.25600111]
 [-0.69879743  0.5681162   0.13957269  0.78044373 -0.07170065]]
[0. 0. 0. 0. 0.]
[[ 0.3490519  -0.0488234  -0.02265608  0.75614407 -0.41718705]
 [-0.5696887   0.36061228 -0.66309885  0.48277823 -0.41553769]
 [-0.20155869 -0.68423968 -0.08393507 -0.52745063  0.07025747]
 [-0.60064967 -0.34109109  0.40971717 -0.14223753  0.01270251]]
[0. 0. 0.]


#### 2. weight initialization using He Normal Initialization

In [21]:
import tensorflow as tf
def he_weight_initialization(fan_in,fan_out):
    limit=tf.sqrt(2/fan_in)
    return tf.random.uniform([fan_in,fan_out],minval=-limit,maxval=limit,dtype=tf.float32)

In [22]:
fan_in=4
fan_out=5
w1=he_weight_initialization(fan_in,fan_out)
print(w1.numpy())
b1=tf.zeros(fan_out)
print(b1.numpy())

[[ 0.1659652  -0.68216205  0.33668357 -0.6306977  -0.18802959]
 [-0.65888673 -0.67944175 -0.7011993   0.6063737   0.30240864]
 [ 0.1771329  -0.43021294  0.4451707  -0.24943516 -0.24667725]
 [-0.44473928 -0.5662832  -0.5618706   0.4629268   0.4670425 ]]
[0. 0. 0. 0. 0.]
